[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_with = "3.12.0"
sqlx = { version = "0.8.3", features = ["postgres", "time", "runtime-tokio-rustls", "uuid"] }
tokio = { version = "1.43.0", features = ["full"] }

# Tracing
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
