[tasks.test_utils]
command = "cargo"
description = "Run the tests in the utils crate"
args = ["test", "--", "utils::utils_test::tests::"]

[tasks.test_crypt]
command = "cargo"
description = "Run the tests in the crypt crate"
args = ["test", "--", "crypt::"]